---
layout: null
---
var index = new elasticlunr.Index;
index.setRef('lunr_id');
index.saveDocument(false);
index.pipeline.remove(elasticlunr.trimmer);
index.addField('pid'); 
index.addField('title'); 
index.addField('wyvern'); 
index.addField('ethereal'); 
index.addField('crone'); 
index.addField('rotfiend'); 
index.addField('therazane'); 
index.addField('grottore'); 
index.addField('siren'); 
index.addField('hagubman'); 
index.addField('howler'); 
index.addField('shrieker'); 
index.addField('sylvan'); 
index.addField('dragon_of_fyresdal'); 
index.addField('leshen'); 
index.addField('harpy'); 
index.addField('doppler'); 
index.addField('slyzard_matriarch'); 
index.addField('endrega_warrior'); 
index.addField('erynias'); 
index.addDoc({"lunr_id":0,"link":"{{ site.baseurl }}/apiarian_phantom/amorphous.html","pid":"amorphous","title":"Unde laudantium sit nam numquam est.","wyvern":"Wow, Bob, wow.","ethereal":"Якушева Вера","crone":"فرزین قنبری","rotfiend":"Mediocre Cotton Lamp","therazane":"ut-omnis/sint.csv","grottore":"Manuscript noisome loathsome squamous unmentionable eldritch comprehension."}); 
index.addDoc({"lunr_id":1,"link":"{{ site.baseurl }}/apiarian_phantom/dank.html","pid":"dank","title":"Et esse neque eum nihil molestiae ipsum consequatur.","wyvern":"There was a fish in the percolator!","ethereal":"Пономарев Арсений Егорович","crone":"فرهاد واعظ","rotfiend":"Fantastic Silk Shirt","therazane":"aperiam.repudiandae/expedita.css","grottore":"Tenebrous swarthy amorphous comprehension ululate hideous blasphemous."}); 
index.addDoc({"lunr_id":2,"link":"{{ site.baseurl }}/apiarian_phantom/loathsome.html","pid":"loathsome","title":"Laudantium nisi sint repellendus consequatur.","wyvern":"There was a fish in the percolator!","ethereal":"Станислав Вячеславович Куликов","crone":"هخامنش لاهوتی DDS","rotfiend":"Heavy Duty Bronze Chair","therazane":"est-est/iusto.flac","grottore":"Unnamable fainted charnel loathsome tenebrous cyclopean."}); 
index.addDoc({"lunr_id":3,"link":"{{ site.baseurl }}/apiarian_phantom/manuscript.html","pid":"manuscript","title":"Eius non eum soluta nulla deleniti.","wyvern":"Where we're from, the birds sing a pretty song, and there's always music in the air.","ethereal":"Матвей Фёдорович Козлов","crone":"سامان قمیشی","rotfiend":"Rustic Wool Computer","therazane":"sit_labore/consequatur.odp","grottore":"Gibbous unmentionable accursed cyclopean stench."}); 
index.addDoc({"lunr_id":4,"link":"{{ site.baseurl }}/apiarian_phantom/noisome.html","pid":"noisome","title":"Impedit eum ipsam corrupti sint rem quia.","wyvern":"Will this sadness that makes me cry my heart out — will it ever end? The answer, of course, is yes. One day the sadness will end.","ethereal":"Пестов Степан","crone":"کامران لنکرانی","rotfiend":"Incredible Wool Clock","therazane":"animi.quae/doloribus.numbers","grottore":"Nameless unutterable accursed non-euclidean manuscript."}); 
index.addDoc({"lunr_id":5,"link":"{{ site.baseurl }}/apiarian_phantom/singular.html","pid":"singular","title":"Assumenda hic aperiam corrupti autem iste.","wyvern":"Where we're from, the birds sing a pretty song, and there's always music in the air.","ethereal":"Никита Дьячков","crone":"گلی مجتهدی IV","rotfiend":"Synergistic Rubber Knife","therazane":"necessitatibus-est/consequuntur.txt","grottore":"Tenebrous singular cat loathsome tentacles immemorial shunned gibbering hideous."}); 
index.addDoc({"lunr_id":6,"link":"{{ site.baseurl }}/apiarian_phantom/stygian.html","pid":"stygian","title":"Quis neque qui mollitia facere alias modi repudiandae odit.","wyvern":"Damn fine coffee! And hot!","ethereal":"Смирнова Регина","crone":"گلرو لاهوتی","rotfiend":"Enormous Marble Coat","therazane":"itaque.occaecati/suscipit.xlsx","grottore":"Unnamable nameless eldritch fungus lurk gibbering."}); 
index.addDoc({"lunr_id":7,"link":"{{ site.baseurl }}/fugas/abnormal.html","pid":"abnormal","title":"Consequatur accusamus id nemo laudantium.","siren":"Wow, Bob, wow.","hagubman":"Анна Гущина","howler":"گیتی موسوی I","shrieker":"Durable Cotton Bottle","sylvan":"dolor-quas/quam.css","dragon_of_fyresdal":"Shunned decadent stygian effulgence fungus."}); 
index.addDoc({"lunr_id":8,"link":"{{ site.baseurl }}/fugas/comprehension.html","pid":"comprehension","title":"Explicabo ipsam voluptas mollitia.","siren":"Cooper, you may be fearless in this world, but there are other worlds.","hagubman":"Евгения Воронцова","howler":"جامین هراتی","shrieker":"Enormous Leather Watch","sylvan":"reiciendis-qui/maiores.html","dragon_of_fyresdal":"Manuscript abnormal amorphous decadent."}); 
index.addDoc({"lunr_id":9,"link":"{{ site.baseurl }}/fugas/cyclopean.html","pid":"cyclopean","title":"Ea et error exercitationem cupiditate.","siren":"Black as midnight on a moonless night.","hagubman":"Михайлова Марина Борисовна","howler":"پریسا مهدی‌پور","shrieker":"Ergonomic Marble Knife","sylvan":"quia_est/id.xls","dragon_of_fyresdal":"Iridescence charnel tenebrous noisome gibbering cyclopean squamous lurk."}); 
index.addDoc({"lunr_id":10,"link":"{{ site.baseurl }}/fugas/gibbering.html","pid":"gibbering","title":"Fuga corrupti est eos deserunt et.","siren":"J'ai une âme solitaire.","hagubman":"Исаева Александра","howler":"همدم هاشمی","shrieker":"Ergonomic Cotton Bench","sylvan":"aut-omnis/numquam.odt","dragon_of_fyresdal":"Gibbous unnamable indescribable madness."}); 
index.addDoc({"lunr_id":11,"link":"{{ site.baseurl }}/fugas/loathsome.html","pid":"loathsome","title":"Sit aliquid assumenda molestiae distinctio illum.","siren":"Sometimes jokes are welcome. Like the one about the kid who said: 'I enjoyed school. It was just the principal of the thing.'","hagubman":"Дмитрий Воронов","howler":"پژوا گلپایگانی","shrieker":"Synergistic Wool Clock","sylvan":"dolorum-consequatur/dolor.txt","dragon_of_fyresdal":"Immemorial lurk noisome comprehension singular stench."}); 
index.addDoc({"lunr_id":12,"link":"{{ site.baseurl }}/fugas/madness.html","pid":"madness","title":"Quas id suscipit earum itaque possimus magni.","siren":"J'ai une âme solitaire.","hagubman":"Петров Геннадий Лукич","howler":"مهرام قنبری","shrieker":"Durable Granite Shirt","sylvan":"aut-soluta/aliquid.csv","dragon_of_fyresdal":"Comprehension spectral hideous dank gibbous antediluvian cyclopean."}); 
index.addDoc({"lunr_id":13,"link":"{{ site.baseurl }}/fugas/unutterable.html","pid":"unutterable","title":"Atque ipsam aut consequatur qui nam eos aspernatur aut.","siren":"There was a fish in the percolator!","hagubman":"Вера Юрьевна Калинина","howler":"آزیتا یاحقی Sr.","shrieker":"Incredible Steel Gloves","sylvan":"sint_iusto/rerum.mov","dragon_of_fyresdal":"Unutterable furtive manuscript fungus shunned."}); 
index.addDoc({"lunr_id":14,"link":"{{ site.baseurl }}/opinicus/antiquarian.html","pid":"antiquarian","title":"Ad tempore et exercitationem.","leshen":"MAY A SMILE BE YOUR UMBRELLA. WE'VE ALL HAD OUR SOCKS TOSSED AROUND.","harpy":"Кудряшова Людмила Викторовна","doppler":"فرزان قهستانی","slyzard_matriarch":"Heavy Duty Linen Hat","endrega_warrior":"aut_id/sint.gif","erynias":"Accursed madness cyclopean unutterable stygian fungus gibbous."}); 
index.addDoc({"lunr_id":15,"link":"{{ site.baseurl }}/opinicus/cyclopean.html","pid":"cyclopean","title":"Consequatur quis et aut aperiam non.","leshen":"I don't wanna talk. I wanna shoot.","harpy":"Королева Елизавета","doppler":"کیانوش میرسپاسی","slyzard_matriarch":"Small Concrete Bag","endrega_warrior":"dolorem.illum/velit.js","erynias":"Manuscript furtive tentacles gambrel."}); 
index.addDoc({"lunr_id":16,"link":"{{ site.baseurl }}/opinicus/decadent.html","pid":"decadent","title":"Quisquam quia soluta rerum omnis et.","leshen":"Will this sadness that makes me cry my heart out — will it ever end? The answer, of course, is yes. One day the sadness will end.","harpy":"Соловьев Леонид","doppler":"دکتر هومان معارف","slyzard_matriarch":"Enormous Steel Bottle","endrega_warrior":"non-ea/et.avi","erynias":"Spectral cat gibbous unutterable."}); 
index.addDoc({"lunr_id":17,"link":"{{ site.baseurl }}/opinicus/indescribable.html","pid":"indescribable","title":"Non vel numquam sunt adipisci nam optio porro dolore.","leshen":"It has been a pleasure speaking to you.","harpy":"Виктория Евгеньевна Жданова","doppler":"نیک خواه فهمیده","slyzard_matriarch":"Practical Wooden Gloves","endrega_warrior":"ut.modi/non.mp4","erynias":"Gibbous ululate fainted swarthy comprehension iridescence lurk."}); 
index.addDoc({"lunr_id":18,"link":"{{ site.baseurl }}/opinicus/non-euclidean.html","pid":"non-euclidean","title":"Sunt sint possimus quia.","leshen":"Audrey, there are many cures for a broken heart. But nothing quite like a trout's leap in the moonlight.","harpy":"Степан Матвеевич Герасимов","doppler":"تناز یادگار","slyzard_matriarch":"Aerodynamic Linen Car","endrega_warrior":"nihil-quia/dignissimos.pptx","erynias":"Iridescence amorphous tenebrous blasphemous."}); 
index.addDoc({"lunr_id":19,"link":"{{ site.baseurl }}/opinicus/spectral.html","pid":"spectral","title":"Eum modi perspiciatis animi qui itaque doloribus.","leshen":"MAY A SMILE BE YOUR UMBRELLA. WE'VE ALL HAD OUR SOCKS TOSSED AROUND.","harpy":"Вероника Андреевна Смирнова","doppler":"مهر دخت مهاجرانی Jr.","slyzard_matriarch":"Sleek Iron Shirt","endrega_warrior":"fuga.adipisci/voluptas.gif","erynias":"Unnamable iridescence charnel manuscript squamous gibbous."}); 
index.addDoc({"lunr_id":20,"link":"{{ site.baseurl }}/opinicus/unutterable.html","pid":"unutterable","title":"Necessitatibus et debitis atque quis quod molestias odit.","leshen":"The owls are not what they seem.","harpy":"Людмила Родионова","doppler":"خانم مهرنیا مجتبایی","slyzard_matriarch":"Mediocre Paper Hat","endrega_warrior":"voluptas-non/quos.mov","erynias":"Gibbous daemoniac charnel fungus noisome ululate blasphemous."}); 
var store = [
{"lunr_id":0,"link":"{{ site.baseurl }}/apiarian_phantom/amorphous.html","pid":"amorphous","title":"Unde laudantium sit nam numquam est.","wyvern":"Wow, Bob, wow.","ethereal":"Якушева Вера","crone":"فرزین قنبری","rotfiend":"Mediocre Cotton Lamp","therazane":"ut-omnis/sint.csv","grottore":"Manuscript noisome loathsome squamous unmentionable eldritch comprehension."}, 
{"lunr_id":1,"link":"{{ site.baseurl }}/apiarian_phantom/dank.html","pid":"dank","title":"Et esse neque eum nihil molestiae ipsum consequatur.","wyvern":"There was a fish in the percolator!","ethereal":"Пономарев Арсений Егорович","crone":"فرهاد واعظ","rotfiend":"Fantastic Silk Shirt","therazane":"aperiam.repudiandae/expedita.css","grottore":"Tenebrous swarthy amorphous comprehension ululate hideous blasphemous."}, 
{"lunr_id":2,"link":"{{ site.baseurl }}/apiarian_phantom/loathsome.html","pid":"loathsome","title":"Laudantium nisi sint repellendus consequatur.","wyvern":"There was a fish in the percolator!","ethereal":"Станислав Вячеславович Куликов","crone":"هخامنش لاهوتی DDS","rotfiend":"Heavy Duty Bronze Chair","therazane":"est-est/iusto.flac","grottore":"Unnamable fainted charnel loathsome tenebrous cyclopean."}, 
{"lunr_id":3,"link":"{{ site.baseurl }}/apiarian_phantom/manuscript.html","pid":"manuscript","title":"Eius non eum soluta nulla deleniti.","wyvern":"Where we're from, the birds sing a pretty song, and there's always music in the air.","ethereal":"Матвей Фёдорович Козлов","crone":"سامان قمیشی","rotfiend":"Rustic Wool Computer","therazane":"sit_labore/consequatur.odp","grottore":"Gibbous unmentionable accursed cyclopean stench."}, 
{"lunr_id":4,"link":"{{ site.baseurl }}/apiarian_phantom/noisome.html","pid":"noisome","title":"Impedit eum ipsam corrupti sint rem quia.","wyvern":"Will this sadness that makes me cry my heart out — will it ever end? The answer, of course, is yes. One day the sadness will end.","ethereal":"Пестов Степан","crone":"کامران لنکرانی","rotfiend":"Incredible Wool Clock","therazane":"animi.quae/doloribus.numbers","grottore":"Nameless unutterable accursed non-euclidean manuscript."}, 
{"lunr_id":5,"link":"{{ site.baseurl }}/apiarian_phantom/singular.html","pid":"singular","title":"Assumenda hic aperiam corrupti autem iste.","wyvern":"Where we're from, the birds sing a pretty song, and there's always music in the air.","ethereal":"Никита Дьячков","crone":"گلی مجتهدی IV","rotfiend":"Synergistic Rubber Knife","therazane":"necessitatibus-est/consequuntur.txt","grottore":"Tenebrous singular cat loathsome tentacles immemorial shunned gibbering hideous."}, 
{"lunr_id":6,"link":"{{ site.baseurl }}/apiarian_phantom/stygian.html","pid":"stygian","title":"Quis neque qui mollitia facere alias modi repudiandae odit.","wyvern":"Damn fine coffee! And hot!","ethereal":"Смирнова Регина","crone":"گلرو لاهوتی","rotfiend":"Enormous Marble Coat","therazane":"itaque.occaecati/suscipit.xlsx","grottore":"Unnamable nameless eldritch fungus lurk gibbering."}, 
{"lunr_id":7,"link":"{{ site.baseurl }}/fugas/abnormal.html","pid":"abnormal","title":"Consequatur accusamus id nemo laudantium.","siren":"Wow, Bob, wow.","hagubman":"Анна Гущина","howler":"گیتی موسوی I","shrieker":"Durable Cotton Bottle","sylvan":"dolor-quas/quam.css","dragon_of_fyresdal":"Shunned decadent stygian effulgence fungus."}, 
{"lunr_id":8,"link":"{{ site.baseurl }}/fugas/comprehension.html","pid":"comprehension","title":"Explicabo ipsam voluptas mollitia.","siren":"Cooper, you may be fearless in this world, but there are other worlds.","hagubman":"Евгения Воронцова","howler":"جامین هراتی","shrieker":"Enormous Leather Watch","sylvan":"reiciendis-qui/maiores.html","dragon_of_fyresdal":"Manuscript abnormal amorphous decadent."}, 
{"lunr_id":9,"link":"{{ site.baseurl }}/fugas/cyclopean.html","pid":"cyclopean","title":"Ea et error exercitationem cupiditate.","siren":"Black as midnight on a moonless night.","hagubman":"Михайлова Марина Борисовна","howler":"پریسا مهدی‌پور","shrieker":"Ergonomic Marble Knife","sylvan":"quia_est/id.xls","dragon_of_fyresdal":"Iridescence charnel tenebrous noisome gibbering cyclopean squamous lurk."}, 
{"lunr_id":10,"link":"{{ site.baseurl }}/fugas/gibbering.html","pid":"gibbering","title":"Fuga corrupti est eos deserunt et.","siren":"J'ai une âme solitaire.","hagubman":"Исаева Александра","howler":"همدم هاشمی","shrieker":"Ergonomic Cotton Bench","sylvan":"aut-omnis/numquam.odt","dragon_of_fyresdal":"Gibbous unnamable indescribable madness."}, 
{"lunr_id":11,"link":"{{ site.baseurl }}/fugas/loathsome.html","pid":"loathsome","title":"Sit aliquid assumenda molestiae distinctio illum.","siren":"Sometimes jokes are welcome. Like the one about the kid who said: 'I enjoyed school. It was just the principal of the thing.'","hagubman":"Дмитрий Воронов","howler":"پژوا گلپایگانی","shrieker":"Synergistic Wool Clock","sylvan":"dolorum-consequatur/dolor.txt","dragon_of_fyresdal":"Immemorial lurk noisome comprehension singular stench."}, 
{"lunr_id":12,"link":"{{ site.baseurl }}/fugas/madness.html","pid":"madness","title":"Quas id suscipit earum itaque possimus magni.","siren":"J'ai une âme solitaire.","hagubman":"Петров Геннадий Лукич","howler":"مهرام قنبری","shrieker":"Durable Granite Shirt","sylvan":"aut-soluta/aliquid.csv","dragon_of_fyresdal":"Comprehension spectral hideous dank gibbous antediluvian cyclopean."}, 
{"lunr_id":13,"link":"{{ site.baseurl }}/fugas/unutterable.html","pid":"unutterable","title":"Atque ipsam aut consequatur qui nam eos aspernatur aut.","siren":"There was a fish in the percolator!","hagubman":"Вера Юрьевна Калинина","howler":"آزیتا یاحقی Sr.","shrieker":"Incredible Steel Gloves","sylvan":"sint_iusto/rerum.mov","dragon_of_fyresdal":"Unutterable furtive manuscript fungus shunned."}, 
{"lunr_id":14,"link":"{{ site.baseurl }}/opinicus/antiquarian.html","pid":"antiquarian","title":"Ad tempore et exercitationem.","leshen":"MAY A SMILE BE YOUR UMBRELLA. WE'VE ALL HAD OUR SOCKS TOSSED AROUND.","harpy":"Кудряшова Людмила Викторовна","doppler":"فرزان قهستانی","slyzard_matriarch":"Heavy Duty Linen Hat","endrega_warrior":"aut_id/sint.gif","erynias":"Accursed madness cyclopean unutterable stygian fungus gibbous."}, 
{"lunr_id":15,"link":"{{ site.baseurl }}/opinicus/cyclopean.html","pid":"cyclopean","title":"Consequatur quis et aut aperiam non.","leshen":"I don't wanna talk. I wanna shoot.","harpy":"Королева Елизавета","doppler":"کیانوش میرسپاسی","slyzard_matriarch":"Small Concrete Bag","endrega_warrior":"dolorem.illum/velit.js","erynias":"Manuscript furtive tentacles gambrel."}, 
{"lunr_id":16,"link":"{{ site.baseurl }}/opinicus/decadent.html","pid":"decadent","title":"Quisquam quia soluta rerum omnis et.","leshen":"Will this sadness that makes me cry my heart out — will it ever end? The answer, of course, is yes. One day the sadness will end.","harpy":"Соловьев Леонид","doppler":"دکتر هومان معارف","slyzard_matriarch":"Enormous Steel Bottle","endrega_warrior":"non-ea/et.avi","erynias":"Spectral cat gibbous unutterable."}, 
{"lunr_id":17,"link":"{{ site.baseurl }}/opinicus/indescribable.html","pid":"indescribable","title":"Non vel numquam sunt adipisci nam optio porro dolore.","leshen":"It has been a pleasure speaking to you.","harpy":"Виктория Евгеньевна Жданова","doppler":"نیک خواه فهمیده","slyzard_matriarch":"Practical Wooden Gloves","endrega_warrior":"ut.modi/non.mp4","erynias":"Gibbous ululate fainted swarthy comprehension iridescence lurk."}, 
{"lunr_id":18,"link":"{{ site.baseurl }}/opinicus/non-euclidean.html","pid":"non-euclidean","title":"Sunt sint possimus quia.","leshen":"Audrey, there are many cures for a broken heart. But nothing quite like a trout's leap in the moonlight.","harpy":"Степан Матвеевич Герасимов","doppler":"تناز یادگار","slyzard_matriarch":"Aerodynamic Linen Car","endrega_warrior":"nihil-quia/dignissimos.pptx","erynias":"Iridescence amorphous tenebrous blasphemous."}, 
{"lunr_id":19,"link":"{{ site.baseurl }}/opinicus/spectral.html","pid":"spectral","title":"Eum modi perspiciatis animi qui itaque doloribus.","leshen":"MAY A SMILE BE YOUR UMBRELLA. WE'VE ALL HAD OUR SOCKS TOSSED AROUND.","harpy":"Вероника Андреевна Смирнова","doppler":"مهر دخت مهاجرانی Jr.","slyzard_matriarch":"Sleek Iron Shirt","endrega_warrior":"fuga.adipisci/voluptas.gif","erynias":"Unnamable iridescence charnel manuscript squamous gibbous."}, 
{"lunr_id":20,"link":"{{ site.baseurl }}/opinicus/unutterable.html","pid":"unutterable","title":"Necessitatibus et debitis atque quis quod molestias odit.","leshen":"The owls are not what they seem.","harpy":"Людмила Родионова","doppler":"خانم مهرنیا مجتبایی","slyzard_matriarch":"Mediocre Paper Hat","endrega_warrior":"voluptas-non/quos.mov","erynias":"Gibbous daemoniac charnel fungus noisome ululate blasphemous."}];