name: ci:test
on:
  push: 
    branches: [main, development, v1*]
  pull_request:
    branches: [main, development, v1*]

jobs:
   rspec:
    runs-on: ubuntu-latest
    steps:
    - name: change imagemagick policy to allow pdf->png conversion.
      run: |
        sudo sed -i 's/^.*policy.*coder.*none.*PDF.*//' /etc/ImageMagick-6/policy.xml
    - name: install ghostscript
      run: sudo apt-get update && sudo apt-get install -y ghostscript
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: check for outdated gems
      run: bundle outdated
    - name: test
      run: bundle exec rspec
